#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch raoNozzle.foam
runApplication gmshToFoam raoNozzle.msh2
runApplication changeDictionary
runApplication transformPoints -scale '(1e-3 1e-3 1e-3)' 
rm -rf 0
restore0Dir
runApplication setInitialNozzle
runApplication $(getApplication)

#------------------------------------------------------------------------------
